# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feff943db762a9421f38c91573aa3401dc8e82c6e55c238a4ae4d327d55c4dcef82283f0b3bca8a40c1f14d5e0b9645614ed1039073001a60871ebe5d52c386e

test:
  secret_key_base: 26131e8099f7856e787109fe0c1dc4f0646e346cb1eb31e6540427eef3fe1552a15f617f368e178b1cb0d72d26de842ffd261bb5859d6ec80e90438e000fa713

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
